// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package media

import (
	"server/api/media"
)

type ControllerV1 struct{}

func NewV1() media.IMediaV1 {
	return &ControllerV1{}
}
